server:
  port: 8080
  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ecommerce-service-java
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
            - Path=/swagger-ui.html